# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpencodeNative < Formula
  desc "Lightweight, native AI coding agent optimized for performance."
  homepage "https://github.com/MerrukTechnology/homebrew-tap"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v1.2.0/opencode-native_darwin_x86_64.tar.gz"
      sha256 "a70f12f6a2c036763282e6a50c6939494c2fc0d0ced4431e38aeccb4f9c71696"

      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v1.2.0/opencode-native_darwin_aarch64.tar.gz"
      sha256 "dee9fc5cec8f68017c7489f6181ef9ee8791f19360a4069613dc7313003afd4a"

      def install
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v1.2.0/opencode-native_linux_x86_64.tar.gz"
      sha256 "ecd9f63ea6882c942979c6de40a66dcdc3f23597add805123400b7500bc6dab4"
      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v1.2.0/opencode-native_linux_aarch64.tar.gz"
      sha256 "3126cc7e2eff457fe7a75270f68251a00e0de07f56b152268c7f96192b2608bd"
      def install
        bin.install "opencode"
      end
    end
  end
end
