# This file was generated by GoReleaser. DO NOT EDIT.
cask "opencode-native" do
  name "opencode-native"
  desc "Lightweight, native AI coding agent optimized for performance."
  homepage "https://github.com/MerrukTechnology/homebrew-tap"
  version "1.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opencode-native"

  on_macos do
    on_intel do
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v#{version}/opencode-native_darwin_x86_64.tar.gz"
      sha256 "00a71c0129ab8c7bb1de478eae1022e41bb0eff24aff55e7fdf920c98f08fe22"
    end
    on_arm do
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v#{version}/opencode-native_darwin_aarch64.tar.gz"
      sha256 "721a487677f2cdd1f9adc04b9ee8be2ab5b8d56f68f4da5efc5297e7bbf1ff21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v#{version}/opencode-native_linux_x86_64.tar.gz"
      sha256 "54c7a833fa12c35733015c9c7bd13e1a69df15f2e1e5250b08311f18d58abcda"
    end
    on_arm do
      url "https://github.com/MerrukTechnology/OpenCode-Native/releases/download/v#{version}/opencode-native_linux_aarch64.tar.gz"
      sha256 "462496c7e6ed3e738a7cce3b6f356fdc6027035d69c526893138415be76d3208"
    end
  end

  # No zap stanza required
end
